
#Modify this workflow yml to execute jUnit test, generate a html file
#and archive html file in workflow step
#understand how git file works
# Official docs of GitHub file
name: Run JUnit Tests

on:
  workflow_dispatch:
    inputs:
      mainClass:
        description: 'Main class to run (full package name)'
        required: true
        default: 'your.package.MainClass'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Compile the code
        run: mvn compile

      - name: Run JUnit tests and generate HTML report
        run: mvn test surefire-report:report

      - name: Upload Surefire HTML test report
        uses: actions/upload-artifact@v3
        with:
          name: surefire-html-report
          path: target/site/surefire-report.html