name: Run Java Class

on:
  workflow_dispatch:
    inputs:
      mainClass:
        description: 'Main class to run (full package name)'
        required: true
        default: 'your.package.MainClass'

jobs:
  run-java:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Install the JDK from Eclipse Temurin
        java-version: '22'

    - name: Compile the code
      run: mvn compile

    - name: Run Maven to execute the specified class
      run: mvn exec:java -Dexec.mainClass=${{ github.event.inputs.mainClass }}
